# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Set GitHub identity
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
    
    - name: Set Git remote with token
      run: |
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Build do projeto React com variáveis
      shell: pwsh
      env:
        VITE_SMTP2GO_API_KEY: ${{ secrets.VITE_SMTP2GO_API_KEY }}
        VITE_SMTP2GO_API_URL: ${{ secrets.VITE_SMTP2GO_API_URL }}
        VITE_EMAIL_CONTACT: ${{ secrets.VITE_EMAIL_CONTACT }}   
      run: |
          Write-Host "Iniciando o build com Vite usando variáveis de ambiente..."
          npm run build  
    # - run: npm ci
    # - run: npm run build --if-present
    # - run: npm test
    - run: npm install
    - run: npm run predeploy
    - run: npm run deploy
